name: Android CI
on: 
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build my Android app
      run: echo building...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Test my Android app
      run: echo testing...

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Publish my Android app
      run: echo publishing
